<?php

/**
 * OrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderItem');
    }
}